packages:
  - 'apps/*'
  - 'packages/agents/*'
  - 'packages/agents/infrastructure/*'
  - 'packages/harvesting/*'
  - 'packages/harvesting/infrastructure/*'
  - 'packages/shared/*'
  - 'packages/shared/ui/*'
  - '!packages/shared/ui/core'
  - 'packages/shared/utils/*'
