apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token # It will create a Secret with same name
  namespace: cert-manager # Must be where cert-manager reads it
spec:
  secretStoreRef: # How ESO talks to our secret backend
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token # Resulting K8s Secret name
    creationPolicy: Owner
  data:
    - secretKey: api-token # Key inside the K8s Secret
      remoteRef:
        key: /cloudflare/api-token # Path in Infisical (set our token here)
