apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml # CRDs/controllers
  - namespace.yaml
  - gateway-class.yaml # GatewayClass for Envoy Gateway
  - gateway.yaml # Public Gateway with HTTP/HTTPS listeners
  - http-redirect-route.yaml # HTTP -> HTTPS redirect
  - certificate.yaml # Explicit Certificate for apex+wildcard

helmCharts:
  - name: gateway-helm
    repo: oci://registry-1.docker.io/envoyproxy
    releaseName: envoy-gateway
    version: "v1.0.3"
    namespace: envoy-gateway
    valuesFile: values.yaml
