apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitea-backup
  namespace: gitea
spec:
  schedule: "0 2 * * *" # Run at 2 AM every day
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: gitea/gitea:1.20
              command:
                - /bin/bash
                - -c
                - >
                  gitea dump -c /etc/gitea/conf/app.ini --file /backup/gitea-dump-$(date +%Y%m%d).zip &&
                  find /backup -name "gitea-dump-*.zip" -type f -mtime +7 -delete
              volumeMounts:
                - name: gitea-data
                  mountPath: /data
                  readOnly: true
                - name: gitea-config
                  mountPath: /etc/gitea/conf
                  readOnly: true
                - name: backup-volume
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: gitea-data
              persistentVolumeClaim:
                claimName: gitea-data
            - name: gitea-config
              configMap:
                name: gitea-config
            - name: backup-volume
              persistentVolumeClaim:
                claimName: gitea-backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-backup
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
