apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
  namespace: gitea
type: Opaque
data:
  db-password: <base64-encoded-db-password>
  gitea-secret-key: <base64-encoded-secret-key>
  gitea-internal-token: <base64-encoded-internal-token>
  gitea-jwt-secret: <base64-encoded-jwt-secret>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      runtimeClassName: kata-containers # This specifies to use Kata Containers
      containers:
        - name: gitea
          image: gitea/gitea:1.20
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: db-password
            - name: GITEA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: gitea-secret-key
            - name: GITEA_INTERNAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: gitea-internal-token
            - name: GITEA_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gitea-secrets
                  key: gitea-jwt-secret
          ports:
            - containerPort: 3000
              name: web
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: gitea-data
              mountPath: /data
            - name: gitea-config
              mountPath: /etc/gitea/conf
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data
        - name: gitea-config
          configMap:
            name: gitea-config
