apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-cluster-secret-store # Matches ExternalSecret.spec.secretStoreRef
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-universal-auth
            namespace: external-secrets
            key: clientId
          clientSecret:
            name: infisical-universal-auth
            namespace: external-secrets
            key: clientSecret
      secretsScope:
        projectSlug: aipacto # Infisical project slug
        environmentSlug: prod # Infisical environment slug
        secretsPath: / # optional; '/' is fine
        recursive: false # optional
