apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hcloud-credentials
  # IMPORTANT: This must be deployed to the same namespace as the hcloud-ccm
  namespace: kube-system
spec:
  # This references the ClusterSecretStore we have configured for our cluster
  # This tells ESO how to authenticate with your secret manager (e.g., Infisical)
  secretStoreRef:
    name: infisical-cluster-secret-store
    kind: ClusterSecretStore

  # Definee the Kubernetes Secret that will be created
  target:
    # The name of the Kubernetes Secret that the Hetzner CCM is looking for
    name: hcloud
    # Ensures the created Secret has the correct labels, owner, etc
    creationPolicy: Owner

  # Map keys from our secret manager to keys in the Kubernetes Secret
  data:
    # The 'secretKey' is the key that will be created inside the Kubernetes Secret
    # The 'remoteRef.key' is the path to our secret in the external vault
    - secretKey: token
      remoteRef:
        key: /hetzner/api-token # Matches Infisical secret

    - secretKey: network
      remoteRef:
        key: /hetzner/network-name # Matches Infisical secret
