apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # The official manifest for the CCM (Cloud Controller Manager)
  - https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.26.0/ccm-networks.yaml
  - externalsecret.yaml
