# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # Validate PR title (becomes squash commit message)
  pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Validate PR title format
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint

  # Single build job that creates all artifacts
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate TypeScript paths
        run: yarn generate-paths

      - name: Build all packages
        run: |
          DO_NOT_TRACK=1 TURBO_TELEMETRY_DISABLED=1 yarn turbo run build

  # Fast checks that run in parallel after build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: |
          DO_NOT_TRACK=1 TURBO_TELEMETRY_DISABLED=1 yarn turbo run lint

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate TypeScript paths
        run: yarn generate-paths

      - name: Run type checks (with cached builds)
        run: |
          DO_NOT_TRACK=1 TURBO_TELEMETRY_DISABLED=1 yarn turbo run build check-types

  security:
    name: Security & Dependencies
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run security and dependency checks
        run: |
          DO_NOT_TRACK=1 TURBO_TELEMETRY_DISABLED=1 yarn turbo run check-secrets check-deps
