name: Deploy Server to Fly.io

on:
  push:
    branches: [main]
    paths:
      - "apps/server/**"
      - "packages/shared/**"
      - "packages/agents/**"
      - ".github/workflows/deploy_server.yaml"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    # Only deploy if CI passed
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Cache Turbo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-deploy-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate TypeScript paths
        run: yarn generate-paths

      - name: Build server
        run: |
          DO_NOT_TRACK=1 TURBO_TELEMETRY_DISABLED=1 yarn turbo run @aipacto/apps-server#build

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --config apps/server/fly.toml
